ALTER TABLE "RoadWalkways" ALTER COLUMN "Geometry" TYPE geometry(MultiLineString, 4326);
ALTER TABLE "RoadWalkways" ADD COLUMN "Walkway_ID" BIGINT;
ALTER TABLE "RoadWalkways" ADD COLUMN "Surface_ID" BIGINT;
ALTER TABLE "RoadWalkways" ADD COLUMN "SubSurface" BIGINT;
ALTER TABLE "RoadWalkways" ADD COLUMN "Kerb_ID" BIGINT;
ALTER TABLE "RoadWalkways" ADD COLUMN "LinkLength" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" ADD COLUMN "RoadLink_I" BIGINT;
ALTER TABLE "RoadWalkways" ADD COLUMN "Surface_Ty" VARCHAR;
ALTER TABLE "RoadWalkways" ADD COLUMN "Length_Km" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" RENAME "Component_" TO "Component";
ALTER TABLE "RoadWalkways" ADD COLUMN "Asset_Type" VARCHAR;
ALTER TABLE "RoadWalkways" ADD COLUMN "Sidewalk_T" VARCHAR;
ALTER TABLE "RoadWalkways" ADD COLUMN "Length_Met" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" ADD COLUMN "Width_Mete" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" ADD COLUMN "Depth_Mete" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" ADD COLUMN "Volume_Met" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" ADD COLUMN "Area_Meter" DOUBLE PRECISION;
ALTER TABLE "RoadWalkways" DROP COLUMN "GISID";
ALTER TABLE "RoadWalkways" DROP COLUMN "Asset_Name";
ALTER TABLE "RoadWalkways" DROP COLUMN "Size_Lengt";
ALTER TABLE "RoadWalkways" DROP COLUMN "Size_Width";
ALTER TABLE "RoadWalkways" DROP COLUMN "Size_Depth";
ALTER TABLE "RoadWalkways" DROP COLUMN "Size_Volum";
ALTER TABLE "RoadWalkways" DROP COLUMN "Quantity";
ALTER TABLE "RoadWalkways" DROP COLUMN "Descriptio";
