CREATE TABLE "SewerAuxAppurtenance_AsBuilt" (
 "rowid" BIGSERIAL,
 "Locality" VARCHAR,
 "MetaID" INTEGER,
 "ID" UUID,
 "Geometry" geometry(Point, 4326),
 "ROTATION" DOUBLE PRECISION,
 "PIPE_YEAR" BIGINT,
 "P_YR_INT" VARCHAR,
 "PIPE_DIAM" DOUBLE PRECISION,
 "S_TYPE" VARCHAR,
 "S_SUB_TYPE" VARCHAR,
 "PIPE_NO" VARCHAR,
 "LP_CODE" VARCHAR,
 "SYMB_ID" VARCHAR,
 "S_PRESS" VARCHAR,
 "S_SIZE" DOUBLE PRECISION,
 "S_SPECIAL" VARCHAR,
 "S_YEAR" BIGINT,
 "SYS_TYPE" VARCHAR,
 "SYSTEM" VARCHAR,
 "COMMENT" VARCHAR,
 "REGION" VARCHAR,
 "NETWORK" VARCHAR,
 "S_MAKE" VARCHAR,
 "S_YR_INT" VARCHAR,
 "S_DRW_NO" VARCHAR,
 PRIMARY KEY("rowid")
);
CREATE INDEX ON "SewerAuxAppurtenance_AsBuilt" USING GIST ("Geometry");
CREATE UNIQUE INDEX ON "SewerAuxAppurtenance_AsBuilt" ("ID");

CREATE TABLE "SewerAuxAppurtenance_Existing" (
 "rowid" BIGSERIAL,
 "Locality" VARCHAR,
 "MetaID" INTEGER,
 "ID" UUID,
 "Geometry" geometry(Point, 4326),
 "ROTATION" DOUBLE PRECISION,
 "PIPE_YEAR" BIGINT,
 "P_YR_INT" VARCHAR,
 "PIPE_DIAM" DOUBLE PRECISION,
 "S_TYPE" VARCHAR,
 "S_SUB_TYPE" VARCHAR,
 "PIPE_NO" VARCHAR,
 "LP_CODE" VARCHAR,
 "SYMB_ID" VARCHAR,
 "S_PRESS" VARCHAR,
 "S_SIZE" DOUBLE PRECISION,
 "S_SPECIAL" VARCHAR,
 "S_YEAR" BIGINT,
 "SYS_TYPE" VARCHAR,
 "SYSTEM" VARCHAR,
 "COMMENT" VARCHAR,
 "REGION" VARCHAR,
 "NETWORK" VARCHAR,
 "S_MAKE" VARCHAR,
 "S_YR_INT" VARCHAR,
 "S_DRW_NO" VARCHAR,
 PRIMARY KEY("rowid")
);
CREATE INDEX ON "SewerAuxAppurtenance_Existing" USING GIST ("Geometry");
CREATE UNIQUE INDEX ON "SewerAuxAppurtenance_Existing" ("ID");

