TRUNCATE TABLE "SewerAuxAppurtenance_AsBuilt";
TRUNCATE TABLE "SewerAuxAppurtenance_Existing";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Rotation" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Symbol_Type" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Symbol_Sub_Type" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Symbol_Code" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Link_Code" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "S_PRESS" TO "Pressure_Rating";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "Pressure_Rating";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Pressure_Rating" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "S_SIZE" TO "Size";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "S_SPECIAL" TO "Special";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "S_YEAR" TO "Year";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "SYS_TYPE" TO "System_Type";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "SYSTEM" TO "System";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "COMMENT" TO "Comment";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "REGION" TO "Region";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" RENAME "S_MAKE" TO "AM_Make";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Integrity" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "Drawing_No" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "ROTATION";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "PIPE_YEAR";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "P_YR_INT";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "PIPE_DIAM";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "S_TYPE";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "S_SUB_TYPE";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "PIPE_NO";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "LP_CODE";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "SYMB_ID";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "NETWORK";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "S_YR_INT";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" DROP COLUMN "S_DRW_NO";
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Rotation" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Symbol_Type" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Symbol_Sub_Type" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Symbol_Code" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Link_Code" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "S_PRESS" TO "Pressure_Rating";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" 	DROP COLUMN "Pressure_Rating";
ALTER TABLE "SewerAuxAppurtenance_AsBuilt" 	ADD COLUMN "Pressure_Rating" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "S_SIZE" TO "Size";
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "S_SPECIAL" TO "Special";
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "S_YEAR" TO "Year";
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "SYS_TYPE" TO "System_Type";
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "SYSTEM" TO "System";
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "COMMENT" TO "Comment";
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "REGION" TO "Region";
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" RENAME "S_MAKE" TO "AM_Make";
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Integrity" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "Drawing_No" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "ROTATION";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "PIPE_YEAR";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "P_YR_INT";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "PIPE_DIAM";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "S_TYPE";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "S_SUB_TYPE";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "PIPE_NO";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "LP_CODE";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "SYMB_ID";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "NETWORK";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "S_YR_INT";
ALTER TABLE "SewerAuxAppurtenance_Existing" DROP COLUMN "S_DRW_NO";
