ALTER TABLE "Building" ADD COLUMN "ID" UUID;
ALTER TABLE "Building" ADD COLUMN "Source" VARCHAR;
ALTER TABLE "Building" ADD COLUMN "Building" VARCHAR;
ALTER TABLE "Building" ADD COLUMN "Facility_Type" VARCHAR;
ALTER TABLE "Building" ADD COLUMN "Area" DOUBLE PRECISION;
ALTER TABLE "Building" ADD COLUMN "Floors" INTEGER;
ALTER TABLE "Building" ADD COLUMN "Streetview" BOOLEAN;
ALTER TABLE "Building" ADD COLUMN "Facility_Number" INTEGER;
ALTER TABLE "Building" ADD COLUMN "MapFeatID" VARCHAR;
