ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_01" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_01" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_01" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_01" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_01" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_02" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_02" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_02" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_02" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_02" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_03" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_03" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_03" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_03" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_03" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_04" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_04" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_04" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_04" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_04" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_05" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_05" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_05" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_05" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_05" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_06" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_06" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_06" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_06" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_06" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_07" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_07" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_07" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_07" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_07" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_08" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_08" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_08" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_08" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_08" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_09" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_09" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_09" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_09" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_09" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolYearIntegrity" TO "Integrity";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolDrawingNo" TO "DrawingNo";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolID" TO "Symbol_Code";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolType" TO "Type";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolSubType" TO "SubType";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolPressureRating" TO "PressureRating";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolSize" TO "Size";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolYear" TO "Year";
ALTER TABLE "WaterAuxAppurtenance_10" RENAME "SymbolMake" TO "AM_Make";
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Link_ID" UUID;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Rotation_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Ward" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Network" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Location" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Location_Options" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Suburb" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "Cost_Function" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "AM_Base_Year" BIGINT;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "AM_Replace_Value" DOUBLE PRECISION;
ALTER TABLE "WaterAuxAppurtenance_10" ADD COLUMN "URL" VARCHAR;
ALTER TABLE "WaterAuxAppurtenance_10" DROP COLUMN "SymbolSpecial";
ALTER TABLE "WaterAuxHouseConnection_10" RENAME "PipeID" TO "Link_Code";
ALTER TABLE "WaterAuxHouseConnection_10" RENAME "SymbolID" TO "Symbol_Code";
