ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Diameter" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Top" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Bottom" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Depth" DOUBLE PRECISION;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Quantity" INTEGER;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Condition" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Condition" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Inlet_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Inlet_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Inlet_Quantity" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "GridInletWidth" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "GridInletLength" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "GridInletAmount" INTEGER;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Accessible" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Structural" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Inspection_Date" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Assessor" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Photo_Notes" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "General" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Condition" VARCHAR;
