ALTER TABLE "ElectricityCables_01" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_02" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_03" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_04" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_05" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_06" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_07" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_08" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_09" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityCables_10" ADD COLUMN "Size" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_01" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_02" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_03" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_04" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_05" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_06" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_07" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_08" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_09" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityLoadsMemo_10" ADD COLUMN "Load_Profile" VARCHAR;
ALTER TABLE "ElectricityTrfrsMemo_01" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_01" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_01" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_02" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_02" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_02" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_03" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_03" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_03" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_04" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_04" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_04" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_05" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_05" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_05" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_06" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_06" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_06" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_07" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_07" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_07" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_08" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_08" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_08" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_09" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_09" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_09" DROP COLUMN "Load_Profile_Data_6";
ALTER TABLE "ElectricityTrfrsMemo_10" ADD COLUMN "Load_Profile_Data_5" BYTEA;
ALTER TABLE "ElectricityTrfrsMemo_10" ADD COLUMN "Exists" BOOLEAN;
ALTER TABLE "ElectricityTrfrsMemo_10" DROP COLUMN "Load_Profile_Data_6";
