ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_01" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_02" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_03" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_04" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_05" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_06" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_07" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_08" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_09" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Functional" VARCHAR;
ALTER TABLE "StormWaterConduitMemo_10" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_01" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_02" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_03" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_04" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_05" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_06" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_07" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_08" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_09" ADD COLUMN "Condition_Description" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "HeadWall_Width" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "HeadWall_Height" DOUBLE PRECISION;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Cover_Shape" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Cover_Type" VARCHAR;
ALTER TABLE "StormwaterJunctionMemo_10" ADD COLUMN "Condition_Description" VARCHAR;
