ALTER TABLE "refComponent_Region" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refComponent_Facility" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refComponent_Department" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refComponent_Supplier" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refComponent_Ward" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refComponent_Suburb" ALTER COLUMN "k" TYPE VARCHAR;
ALTER TABLE "refProject_CostCentre" ALTER COLUMN "k" TYPE VARCHAR;