ALTER TABLE "ScadaMain" ADD COLUMN "WarningLow" DOUBLE PRECISION;
ALTER TABLE "ScadaMain" ADD COLUMN "WarningHigh" DOUBLE PRECISION;
ALTER TABLE "ScadaMain" ADD COLUMN "LimitLow" DOUBLE PRECISION;
ALTER TABLE "ScadaMain" ADD COLUMN "LimitHigh" DOUBLE PRECISION;
