ALTER TABLE "AssetComponent" ADD COLUMN "Room_Name" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "Building_Name" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "Fleet_Reg_Year" INTEGER;
ALTER TABLE "AssetComponent" ADD COLUMN "Floor" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "AdditionsNature" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "CaseNumber" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "CashGenerating" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "DateCreated" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "DateLastFinMonth" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "DateLastRenewed" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "DepreciationBudgetNr_Credit" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "DepreciationBudgetNr_Debit" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "FuncLocPath" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "Impairment_Review_Date" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "InsuranceClaimed" BOOLEAN;
ALTER TABLE "AssetComponent" ADD COLUMN "InsurancePolicyNr" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "LastMaintenanceDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "ReplacedComponents" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationAccuracy" INTEGER;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationMethod" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluedBy" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "SoldTo" VARCHAR;
ALTER TABLE "AssetComponent" ADD COLUMN "UpgradeDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "VerificationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "VerificationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponent" ADD COLUMN "YearConstruct_CG" INTEGER;
ALTER TABLE "AssetComponent" ADD COLUMN "YearRenewed_CG" INTEGER;
ALTER TABLE "AssetComponent" ADD COLUMN "AdditionsClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "AdditionsOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "DisposalProfitLoss" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "DRC" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "EUL_Adjusted" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "FairValueLessCostSell" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "InsuranceAmount" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "InsuranceCover" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationReserveClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationReserveFinYTD" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationReserveFinYTDDepr" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationReserveFinYTDImp" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationReserveOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevaluationRUL" INTEGER;
ALTER TABLE "AssetComponent" ADD COLUMN "RevImpairmentAll" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "RevImpairmentClose" DOUBLE PRECISION;
ALTER TABLE "AssetComponent" ADD COLUMN "ValueInUse" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "Room_Name" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "Building_Name" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "Fleet_Reg_Year" INTEGER;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "Floor" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "AdditionsNature" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "CaseNumber" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "CashGenerating" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DateCreated" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DateLastFinMonth" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DateLastRenewed" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DepreciationBudgetNr_Credit" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DepreciationBudgetNr_Debit" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "FuncLocPath" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "Impairment_Review_Date" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "InsuranceClaimed" BOOLEAN;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "InsurancePolicyNr" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "LastMaintenanceDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "ReplacedComponents" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationAccuracy" INTEGER;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationMethod" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluedBy" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "SoldTo" VARCHAR;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "UpgradeDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "VerificationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "VerificationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "YearConstruct_CG" INTEGER;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "YearRenewed_CG" INTEGER;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "AdditionsClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "AdditionsOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DisposalProfitLoss" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "DRC" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "EUL_Adjusted" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "FairValueLessCostSell" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "InsuranceAmount" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "InsuranceCover" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationReserveClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationReserveFinYTD" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationReserveFinYTDDepr" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationReserveFinYTDImp" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationReserveOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevaluationRUL" INTEGER;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevImpairmentAll" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "RevImpairmentClose" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometry" ADD COLUMN "ValueInUse" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "Room_Name" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "Building_Name" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "Fleet_Reg_Year" INTEGER;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "Floor" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "AdditionsNature" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "CaseNumber" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "CashGenerating" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DateCreated" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DateLastFinMonth" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DateLastRenewed" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DepreciationBudgetNr_Credit" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DepreciationBudgetNr_Debit" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "FuncLocPath" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "Impairment_Review_Date" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "InsuranceClaimed" BOOLEAN;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "InsurancePolicyNr" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "LastMaintenanceDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "ReplacedComponents" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationAccuracy" INTEGER;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationMethod" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluedBy" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "SoldTo" VARCHAR;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "UpgradeDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "VerificationLastDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "VerificationNextDate" TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "YearConstruct_CG" INTEGER;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "YearRenewed_CG" INTEGER;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "AdditionsClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "AdditionsOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DisposalProfitLoss" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "DRC" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "EUL_Adjusted" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "FairValueLessCostSell" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "InsuranceAmount" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "InsuranceCover" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationReserveClosing" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationReserveFinYTD" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationReserveFinYTDDepr" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationReserveFinYTDImp" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationReserveOpening" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevaluationRUL" INTEGER;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevImpairmentAll" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "RevImpairmentClose" DOUBLE PRECISION;
ALTER TABLE "AssetComponentGeometryDeltas" ADD COLUMN "ValueInUse" DOUBLE PRECISION;
