CREATE TABLE "AuthLog" (
 "rowid" BIGSERIAL,
 "user" VARCHAR,
 "login_time" TIMESTAMP WITHOUT TIME ZONE,
 PRIMARY KEY("rowid")
);

CREATE TABLE "Condition_Assessment" (
 "rowid" BIGSERIAL,
 "ID" UUID,
 "Locality" VARCHAR,
 "MetaID" INTEGER,
 "Geometry" geometry(MultiLineString, 4326),
 "Old_PipeNr" VARCHAR,
 "Pipe_Nr" VARCHAR,
 "Contract" VARCHAR,
 "Pipe_Class" VARCHAR,
 "Pipe_Diameter" DOUBLE PRECISION,
 "Install_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Pipe_Material" VARCHAR,
 "Geography_Source" VARCHAR,
 "Start_Station" VARCHAR,
 "End_Station" VARCHAR,
 "MIG_Pipe_Length" DOUBLE PRECISION,
 "Inspected_Distance" DOUBLE PRECISION,
 "Adj_Nom_Pipe_Length" DOUBLE PRECISION,
 "MIG_Source" VARCHAR,
 "Measure_Pipe_Length" DOUBLE PRECISION,
 "Low_Wheel_Distance" DOUBLE PRECISION,
 "High_Wheel_Distance" DOUBLE PRECISION,
 "Low_Feet" DOUBLE PRECISION,
 "Low_Inches" DOUBLE PRECISION,
 "High_Feet" DOUBLE PRECISION,
 "High_Inches" DOUBLE PRECISION,
 "CL_Feature_Distance" DOUBLE PRECISION,
 "VO_First_Joint" VARCHAR,
 "VO_Barrel_Pipe" VARCHAR,
 "VO_Second_Joint" VARCHAR,
 "VS_Inspection_Date" TIMESTAMP WITHOUT TIME ZONE,
 "IMU_Inspection_Length" DOUBLE PRECISION,
 "First_Joint_IMU_Station" VARCHAR,
 "Second_Joint_IMU_Station" VARCHAR,
 "First_Joint_Elevation" DOUBLE PRECISION,
 "Second_Joint_Elevation" DOUBLE PRECISION,
 "Pipe_Pure_GIS_ID" VARCHAR,
 "USJ_Pure_GIS_ID" VARCHAR,
 "DSJ_Pure_GIS_ID" VARCHAR,
 "IMU_Inspection_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Leak_Present" VARCHAR,
 "Gas_Pocket_Present" VARCHAR,
 "Pipe_Material_Change" VARCHAR,
 "Distance_From_TrackPoint" VARCHAR,
 "Inspection_Point" VARCHAR,
 "Pocket_Inspection_Source" VARCHAR,
 "Pocket_Inspection_Date" TIMESTAMP WITHOUT TIME ZONE,
 "PWA_Source" VARCHAR,
 "PWA_Result" VARCHAR,
 "Pure_Reference_Number" VARCHAR,
 "Total_EM_WB" INTEGER,
 "Q1" INTEGER,
 "Q2" INTEGER,
 "Q3" INTEGER,
 "Q4" INTEGER,
 "Weighted_EM_WBs" INTEGER,
 "Break_Region_Location" VARCHAR,
 "NumberOfWBs_By_Region" VARCHAR,
 "Anomaly_Location" DOUBLE PRECISION,
 "EM_Notes" VARCHAR,
 "EM_Odometer" DOUBLE PRECISION,
 "EM_Inspection_Length" DOUBLE PRECISION,
 "EM_Inspection_Source" VARCHAR,
 "EM_Inspection_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Anomaly_Present" VARCHAR,
 "Anomaly_Location_Enhanced" DOUBLE PRECISION,
 "Clock_Position" VARCHAR,
 "Detector_Numbers" VARCHAR,
 "Enhanced_EM_ToolType" VARCHAR,
 "Enhanced_EM_InspectionDate" TIMESTAMP WITHOUT TIME ZONE,
 "Start_Monitor_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Stop_Monitor_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Critical_Pipe" VARCHAR,
 "Repair_Date" TIMESTAMP WITHOUT TIME ZONE,
 "Repair_Status" VARCHAR,
 "Repair_Type" VARCHAR,
 "EM_Rating" INTEGER,
 "VS_Rating" INTEGER,
 "SU_Rating" INTEGER,
 "Condition_Rating" DOUBLE PRECISION,
 "FEA_Curve" VARCHAR,
 "Ref_Curve_Contract" VARCHAR,
 "Ref_Curve_Class" VARCHAR,
 "Ref_Curve_EarthCover" DOUBLE PRECISION,
 "FEA_Model" INTEGER,
 "Microcracking_Limit" INTEGER,
 "Visible_Cracking_Limit" INTEGER,
 "Yield_Limit" INTEGER,
 "Strength_Limit" INTEGER,
 "Segment_ID" VARCHAR,
 "LoF" DOUBLE PRECISION,
 "DIR" DOUBLE PRECISION,
 "CoF" DOUBLE PRECISION,
 "Mitigation_Factor" DOUBLE PRECISION,
 "Risk" DOUBLE PRECISION,
 "System_Mapsheet_ID" VARCHAR,
 "Hydraulic_Zone" VARCHAR,
 "High_Hydraulic_Zone" VARCHAR,
 "Invert" DOUBLE PRECISION,
 "Ground_Elevation" DOUBLE PRECISION,
 "Ground_Cover" DOUBLE PRECISION,
 "Invert_Ground_Source" VARCHAR,
 "Max_MO_Pressure" DOUBLE PRECISION,
 "Max_M_Pressure" DOUBLE PRECISION,
 "Min_MO_Pressure" DOUBLE PRECISION,
 "Min_M_Pressure" DOUBLE PRECISION,
 "Pressure" DOUBLE PRECISION,
 "Design_Soil_Density" DOUBLE PRECISION,
 "Tested_Soil_Density" DOUBLE PRECISION,
 "Tested_Soil_Resist" DOUBLE PRECISION,
 "Date_Soil_Test" TIMESTAMP WITHOUT TIME ZONE,
 "Manufacturer" VARCHAR,
 "Plant_No" VARCHAR,
 "Nominal_Pipe_Diameter" DOUBLE PRECISION,
 "Cylinder_Gage" VARCHAR,
 "Cylinder_Area" DOUBLE PRECISION,
 "Cylinder_Test_Pressure" DOUBLE PRECISION,
 "Min_Yield_Strength" DOUBLE PRECISION,
 "Nom_Cylinder_Diameter" DOUBLE PRECISION,
 "Wire_Diameter" DOUBLE PRECISION,
 "Wire_Class" VARCHAR,
 "Wire_Area" DOUBLE PRECISION,
 "Wraps_per_Unit" DOUBLE PRECISION,
 "Wire_Pitch" VARCHAR,
 "Total_Wire_Wraps" BIGINT,
 "Wire_Strength" DOUBLE PRECISION,
 "Wrapping_Stress" DOUBLE PRECISION,
 "Dynamometer" DOUBLE PRECISION,
 "Pressure_At_Zero" DOUBLE PRECISION,
 "Resultant_Compression" DOUBLE PRECISION,
 "Initial_Cylinder" DOUBLE PRECISION,
 "Resultant_Cylinder" DOUBLE PRECISION,
 "Cylinder_Stress" DOUBLE PRECISION,
 "Min_Comp_Strength" DOUBLE PRECISION,
 "Core_Thickness" DOUBLE PRECISION,
 "Coating_Thickness" DOUBLE PRECISION,
 "Coating_Type" VARCHAR,
 "Spigot_Ring" DOUBLE PRECISION,
 "Bell_Ring" VARCHAR,
 "Joint_Depth" DOUBLE PRECISION,
 "Creep" DOUBLE PRECISION,
 "Design_Standard" VARCHAR,
 "Design_Opr_Pressure" DOUBLE PRECISION,
 "Design_Surge_Pressure" DOUBLE PRECISION,
 "Design_Test_Pressure" DOUBLE PRECISION,
 "Design_Ground_Cover" DOUBLE PRECISION,
 "Loading_Conditions" VARCHAR,
 "Manufacturer_ID" VARCHAR,
 "Notes" VARCHAR,
 "Approximate_Lay" DOUBLE PRECISION,
 "PipelineID" UUID,
 PRIMARY KEY("rowid")
);
CREATE INDEX "idx_Condition_Assessment_Geometry" ON "Condition_Assessment" USING GIST ("Geometry");

CREATE TABLE "Metadata" (
 "rowid" SERIAL,
 "value" VARCHAR,
 PRIMARY KEY("rowid")
);

CREATE TABLE "Pure_Pipe" (
 "rowid" BIGSERIAL,
 "Locality" VARCHAR,
 "MetaID" INTEGER,
 "Geometry" geometry(MultiLineString, 4326),
 "Pipe_Diameter" DOUBLE PRECISION,
 "Pipe_Material" VARCHAR,
 "Install_Date" TIMESTAMP WITHOUT TIME ZONE,
 "GeogSource" VARCHAR,
 "LeakDetIns" VARCHAR,
 "WallThick" DOUBLE PRECISION,
 "LeakPres" BOOLEAN,
 "GPPres" BOOLEAN,
 "LkDetDate" TIMESTAMP WITHOUT TIME ZONE,
 "ID" UUID,
 PRIMARY KEY("rowid")
);
CREATE INDEX "idx_Pure_Pipe_Geometry" ON "Pure_Pipe" USING GIST ("Geometry");
CREATE UNIQUE INDEX "idx_Pure_Pipe_ID" ON "Pure_Pipe" ("ID");
