CREATE TABLE "furniture" (
 "_id" BIGSERIAL,
 "geometry" geometry(Geometry, 4326),
 "locality" VARCHAR,
 "data_provider" VARCHAR,
 "furniture_type" VARCHAR,
 "auth_name" VARCHAR,
 "street" VARCHAR,
 "town" VARCHAR,
 "suburb" VARCHAR,
 "extension" VARCHAR,
 "library_reference" VARCHAR,
 "contractor" VARCHAR,
 "contract_number" BIGINT,
 "contract_description" VARCHAR,
 "completion_date" VARCHAR,
 "date_as_built" VARCHAR,
 "date_as_built_register" VARCHAR,
 "plan_num1" VARCHAR,
 "street_name" VARCHAR,
 "stop_reference" VARCHAR,
 "peak_am" VARCHAR,
 "peak_pm" VARCHAR,
 "exist_stop_facility" VARCHAR,
 "prop_stop_facility" VARCHAR,
 "exist_shelter_type" VARCHAR,
 "prop_shelter_type" VARCHAR,
 "existing_modules" VARCHAR,
 "remarks" VARCHAR,
 "speed_humb_number" VARCHAR,
 "ward_number" VARCHAR,
 "road_number" VARCHAR,
 "lat" VARCHAR,
 "long" VARCHAR,
 "category" VARCHAR,
 "type_1" VARCHAR,
 "type_2" VARCHAR,
 "road_class" VARCHAR,
 "illumination" BOOLEAN,
 "code_description" VARCHAR,
 "sign_code_new" VARCHAR,
 PRIMARY KEY("_id")
);
CREATE INDEX ON "furniture" USING GIST ("geometry");

DROP TABLE "road_sign";
