ALTER TABLE "condition" ADD COLUMN "combine_index" BIGINT;
ALTER TABLE "condition" ADD COLUMN "visual_condition" VARCHAR;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rem_surface_life" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rem_structural_life" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_maintenance_type" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rec_maintenance_type" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_maintenance_cost" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rec_maintenance_cost" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_rehab_type" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rec_rehab_type" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_rehab_cost" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rec_rehab_cost" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rebuild_text" VARCHAR;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rec_surf_text" VARCHAR;
ALTER TABLE "recommended_maintenance" ADD COLUMN "rebuild_index" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "reseal_index" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "reseal_category" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_surface_cost" BIGINT;
ALTER TABLE "recommended_maintenance" ADD COLUMN "min_surf_text" BIGINT;
ALTER TABLE "recommended_maintenance" DROP COLUMN "rem_surface_lif";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rem_struc_li";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_maintenance_ty";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rec_maintenance_ty";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_maintenance_co";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rec_maintenance_co";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_rehab_ty";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rec_rehab_ty";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_rehab_co";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rec_rehab_co";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rebuild_tex";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rec_surf_tex";
ALTER TABLE "recommended_maintenance" DROP COLUMN "rebuild_ind";
ALTER TABLE "recommended_maintenance" DROP COLUMN "reseal_inde";
ALTER TABLE "recommended_maintenance" DROP COLUMN "reseal_cate";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_surface_cos";
ALTER TABLE "recommended_maintenance" DROP COLUMN "min_surf_tex";
ALTER TABLE "road_static" ADD COLUMN "exist_stop_facility" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "prop_stop_facility" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "traditional_auth" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "roads_per_ward" BIGINT;
ALTER TABLE "road_static" ADD COLUMN "caller_name" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "caller_request" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "traffic_class" BIGINT;
ALTER TABLE "road_static" ADD COLUMN "traffic_text" VARCHAR;
ALTER TABLE "road_static" ADD COLUMN "rcam_class_text" VARCHAR;
ALTER TABLE "road_static" DROP COLUMN "exist_stop_fac";
ALTER TABLE "road_static" DROP COLUMN "prop_stop_fac";
ALTER TABLE "road_static" DROP COLUMN "trad_auth";
ALTER TABLE "road_static" DROP COLUMN "rds_per_ward";
ALTER TABLE "road_static" DROP COLUMN "cllr_name";
ALTER TABLE "road_static" DROP COLUMN "cllr_request";
ALTER TABLE "road_static" DROP COLUMN "traffic_cla" CASCADE;
ALTER TABLE "road_static" DROP COLUMN "traffic_tex" CASCADE;
ALTER TABLE "road_static" DROP COLUMN "comb_index";
