CREATE INDEX ON "condition" ("sci");
ALTER TABLE "recommended_maintenance" DROP COLUMN "surface_cost_code_id";
ALTER TABLE "recommended_maintenance" DROP COLUMN "pavement_cost_code_id";
ALTER TABLE "recommended_maintenance" DROP COLUMN "fmtn_cost_code_id";
ALTER TABLE "road_static" ADD COLUMN "subplace_code" BIGINT;
ALTER TABLE "road_static" DROP COLUMN "code_name";
ALTER TABLE "road_static" DROP COLUMN "asset_id";
ALTER TABLE "road_static" DROP COLUMN "asset_type_desc";
ALTER TABLE "road_static" DROP COLUMN "component_type_id";
ALTER TABLE "road_static" DROP COLUMN "sidewalk_pe";
ALTER TABLE "road_static" DROP COLUMN "kerb_pe";
ALTER TABLE "road_static" DROP COLUMN "surface_asset_id";
ALTER TABLE "road_static" DROP COLUMN "surface_component_id";
ALTER TABLE "road_static" DROP COLUMN "surface_component_type_id";
ALTER TABLE "road_static" DROP COLUMN "pavement_asset_id";
ALTER TABLE "road_static" DROP COLUMN "pavement_component_id";
ALTER TABLE "road_static" DROP COLUMN "pavement_component_type_id";
ALTER TABLE "road_static" DROP COLUMN "fmtn_asset_id";
ALTER TABLE "road_static" DROP COLUMN "fmtn_component_id";
ALTER TABLE "road_static" DROP COLUMN "fmtn_component_type_id";
ALTER TABLE "road_static" DROP COLUMN "storm_chan";
ALTER TABLE "road_static" DROP COLUMN "subplace_c";
ALTER TABLE "road_static" DROP COLUMN "count_geom";
ALTER TABLE "road_static" DROP COLUMN "seq_flag";
