require_relative 'view-builder'

# see create-views-water.rb for an explanation of how these were built

scenarios = [["04", "Existing"], ["05", "Future"], ["02", "AsBuilt"], ["03", "Construction"], ["01", "Abandoned"]]

sewer_gravity = {
	:SewerGravity => %w(
		Locality
		ID
		From_ID
		To_ID
		Link_Type
		From_Structure_Code
		To_Structure_Code
		Exists
		From_Ground_Level
		To_Ground_Level
		From_Cover_Level
		To_Cover_Level
		From_Invert_Level
		To_Invert_Level
		Diameter
		Original_Diameter
		SWMM_Geometry_1
		SWMM_Geometry_2
		SWMM_Geometry_3
		SWMM_Geometry_4
		SWMM_Model
		Design_Group
		Planning_Item
		User_Defined_Length
		Length_Type
		Calculated_Slope
		Slope_Type
		Infiltration_Rate
		Additional_Pipe_Length
		Storm
		Cost_Function
		Design_Spare_Capacity
		User_Flag
		Geometry
		Design_Min_Velocity
		MetaID
	),
	:SewerGravityMemo => %w(
		Material
		Nominal_Diameter
		Inside_Diameter
		Year
		Year_Integrity
		Special
		System_Type
		System
		Name
		Sub_Name
		Comment
		Region
		MP_Item_Type
		MP_Item_No
		MP_Project_No
		MP_Project_Descr
		MP_New_Diam
		MP_Par_Diam
		MP_Design_Flow
		MP_Design_Type
		MP_Year
		MP_Comment
		MP_Cost_Detail
		MP_Cost_FN
		MP_Extra_Cost_Fact
		Future_System_Type
		Future_System
		AM_Make
		AM_Type
		AM_ID_No
		AM_Utilization
		AM_Utilization_Integ
		AM_Base_Year
		AM_Replace_Value
		Locality_Integrity
		Material_Integrity
		Diameter_Integrity
		Slope_Integrity
		Drawing_No
		GIS_Diameter
		GIS_Gradient
		Old_GIS_ID
		Old_GIS_Int
		Sur_US_IL
		Sur_DS_IL
		Sur_Slope
		Sur_Integ
		Cctv_Diam
		Cctv_Material
		Existing_Drainage_Area
		Future_Drainage_Area
	),
	:SewerGravityResults => %w(
		Full_Flow
		Full_Velocity
		Max_Flow
		Min_Flow
		Max_Flow_Velocity
		Max_Flow_Depth
		Min_Flow_Velocity
		Min_Flow_Depth
		Max_Overflow_Rate
		Hydraulic_Spare_Capacity
		Absolute_Spare_Capacity
		Relative_Spare_Capacity
		Design_Flow
		US_Cont_Pump_Flow
		Timestep_0
		Timestep_1
		Timestep_2
		Timestep_3
		Timestep_4
		Timestep_5
		Timestep_6
		Timestep_7
		Timestep_8
		Timestep_9
		Timestep_10
		Timestep_11
		Timestep_12
		Timestep_13
		Timestep_14
		Timestep_15
		Timestep_16
		Timestep_17
		Timestep_18
		Timestep_19
		Timestep_20
		Timestep_21
		Timestep_22
		Timestep_23
	)
}

sewer_pump = {
	:SewerPump => %w(
		Locality
		ID
		From_ID
		Exists
		Pump_Index
		Pump_Type
		Cost_Function
		Initial_Status
		On_Level
		Off_Level
		Design_Spare_Capacity
		Design_Down_Size
		SWMM_X1
		SWMM_Y1
		SWMM_X2
		SWMM_Y2
		SWMM_X3
		SWMM_Y3
		SWMM_X4
		SWMM_Y4
		SWMM_X5
		SWMM_Y5
		SWMM_X6
		SWMM_Y6
		SWMM_X7
		SWMM_Y7
		SWMM_X8
		SWMM_Y8
		SWMM_X9
		SWMM_Y9
		SWMM_X10
		SWMM_Y10
		MetaID
	),
	:SewerPumpMemo => %w(
		Impeller
		Speed
		Power
		Static_Head
		Pump_Flow
		Pump_Head
		PS_Oper_Standby
		Year
		Year_Integrity
		System_Type
		System
		Name
		Sub_Name
		Comment
		Region
		MP_Item_Type
		MP_Item_No
		MP_Project_No
		MP_Project_Descr
		MP_Pump_Flow
		MP_Pump_Head
		MP_Design_Flow
		MP_Design_Type
		MP_Year
		MP_Comment
		MP_Cost_Detail
		MP_Cost_FN
		MP_Extra_Cost_Fact
		Future_System_Type
		Future_System
		AM_Make
		AM_Type
		AM_ID_No
		AM_Utilization
		AM_Utilization_Integ
		AM_Base_Year
		AM_Replace_Value
		Pump_Integrity
		Flow_Integrity
		Drawing_No
		Existing_Drainage_Area
		Future_Drainage_Area
	),
	# NOTE: Removed [Design_Spare_Capacity, Design_Down_Size] from here, because they already appear in the SewerPump table
	:SewerPumpResults => %w(
		Design_Flow
		Max_Inflow
		Hydraulic_Spare_Capacity
		Absolute_Spare_Capacity
		Relative_Spare_Capacity
	)
}

sewer_rising = {
	:SewerRising => %w(
		Locality
		ID
		From_ID
		To_ID
		Link_Code
		Link_Type
		From_Structure_Code
		To_Structure_Code
		Exists
		From_Cover_Level
		To_Cover_Level
		From_Invert_Level
		To_Invert_Level
		Percent_Of_Flow
		Diameter
		Original_Diameter
		Design_Group
		Planning_Item
		Calculated_Length
		Length_Type
		Cost_Function
		User_Flag
		Geometry
		Design_Min_Velocity
		Design_Maximum_Velocity
		MetaID
  	),
	:SewerRisingMemo => %w(
		Material
		Pressure_Rating
		Nominal_Diameter
		Inside_Diameter
		Year
		Year_Integrity
		Special
		System_Type
		System
		Name
		Sub_Name
		Comment
		Region
		MP_Item_Type
		MP_Item_No
		MP_Project_No
		MP_Project_Descr
		MP_New_Diam
		MP_Par_Diam
		MP_Design_Flow
		MP_Design_Type
		MP_Year
		MP_Comment
		MP_Cost_Detail
		MP_Cost_FN
		MP_Extra_Cost_Fact
		Future_System_Type
		Future_System
		AM_Make
		AM_Type
		AM_ID_No
		AM_Utilization
		AM_Utilization_Integ
		AM_Base_Year
		AM_Replace_Value
		Locality_Integrity
		Material_Integrity
		Pressure_Integrity
		Diameter_Integrity
		Drawing_No
		GIS_Diameter
		Old_GIS_ID
		Old_GIS_Int
		Existing_Drainage_Area
		Future_Drainage_Area
  	),
	:SewerRisingResults => %w(
		Total_Lag
		Max_Inflow
		Max_Flow
		Min_Flow
		Max_Overflow_Rate
		Min_Velocity
		Max_Velocity
		Timestep_0
		Timestep_1
		Timestep_2
		Timestep_3
		Timestep_4
		Timestep_5
		Timestep_6
		Timestep_7
		Timestep_8
		Timestep_9
		Timestep_10
		Timestep_11
		Timestep_12
		Timestep_13
		Timestep_14
		Timestep_15
		Timestep_16
		Timestep_17
		Timestep_18
		Timestep_19
		Timestep_20
		Timestep_21
		Timestep_22
		Timestep_23
  	)
}

sewer_structures = {
	:SewerStructure => %w(
		Locality
		ID
		Structure_Code
		Structure_Type
		Ground_Level
		Cover_Level
		User_Depth
		Planning_Item
		System_Area
		Depth
		Geometry
		MetaID
	),
	:SewerStructureMemo => %w(
		Material
		PS_Flow
		PS_Head
		Year
		Year_Integrity
		System_Type
		System
		Name
		Sub_Name
		Comment
		Region
		WSDP_Name
		WSDP_Receiving_Stream
		WSDP_Capacity
		WSDP_Fut_Capacity
		Catchment_PDDWF
		Fut_Catchment_PDDWF
		Sump_Volume
		Future_Sump_Volume
		MP_Item_Type
		MP_Item_No
		MP_Project_No
		MP_Project_Descr
		MP_PS_Flow
		MP_PS_Head
		MP_Design_Flow
		MP_Design_Type
		MP_Year
		MP_Comment
		MP_Cost_Detail
		MP_Cost_FN
		MP_Extra_Cost_Fact
		Future_System_Type
		Future_System
		Future_Develop
		Informal_Develop
		AM_Make
		AM_Type
		AM_ID_No
		AM_Utilization
		AM_Utilization_Integrity
		AM_Base_Year
		AM_Replace_Value
		Locality_Integrity
		Material_Integrity
		Cover_Level_Integrity
		Drawing_No
	),
	:SewerStructureResults => %w(
		Min_US_Flow
		Max_US_Flow
		Peak_US_Cont_Pump
		Total_US_Flow_Volume
		Local_US_Flow_Volume
		Max_Overflow_Ratw
		Simulated_US_Flow_Volume
		Infiltration_Volume
		Total_US_AADD
		Total_Flow_Percent_AADD
		US_Cont_Pumps
		US_Variable_Pumps
		US_Sump_Pumps
		US_Diversions
		US_Gravity_Length
		US_Rising_Length
		US_Additional_Length
		US_No_UH_1
		US_No_UH_2
		US_No_UH_3
		US_No_UH_4
		US_No_UH_5
		US_No_UH_6
		US_No_UH_7
		US_No_UH_8
		US_No_UH_9
		US_No_UH_10
		US_No_UH_11
		US_No_UH_12
		US_No_UH_13
		US_No_UH_14
		US_No_UH_15
		US_No_UH_16
		US_No_UH_17
		US_No_UH_18
		US_No_UH_19
		US_No_UH_20
		US_No_User_Hydrograph
		Infiltration_Percent_Volume
	)
}

options = {:has_geometry => true, :only_drop_views => (ARGV[0] == "-d")}
print(ViewBuilder.build_view_statement("SewerGravityCombined", sewer_gravity, scenarios, options))
print(ViewBuilder.build_view_statement("SewerPumpCombined", sewer_pump, scenarios, options))
print(ViewBuilder.build_view_statement("SewerRisingCombined", sewer_rising, scenarios, options))
print(ViewBuilder.build_view_statement("SewerStructureCombined", sewer_structures, scenarios, options))
